NIPOSoftwareBV/Nfield-SDK

Library/Extensions/HttpResponseMessageExtensions.cs
Library/Infrastructure/NfieldErrorCode.cs

In the Nfield API we stop using reason phrase because it has become less supported as we upgrade the Azure deployments.
It is also no longer supported in [HTTP/2](https://http2.github.io/http2-spec/):
> HTTP/2 does not define a way to carry the version or reason phrase that is included in an HTTP/1.1 status line

Use content instead of reason phrase

---

Library/BuildPackage.cmd
Library/Infrastructure/NfieldSdkInitializer.cs
Library/Models/InvitationBatch.cs
Library/Models/InvitationBatchWithFilter.cs
Library/Models/SurveyVarFile.cs
Library/Nfield.SDK.csproj
Library/Services/INfieldSurveyVarFileService.cs
Library/Services/Implementation/NfieldSurveyVarFileService.cs
Tests/Nfield.SDK.Tests.csproj
Tests/Services/NfieldSurveyVarFileServiceTests.cs
appveyor.yml

The VAR-file is currently obtained from the questionnaire file through Odin Developer, in a ‘manual’ process. Customers want to make VAR-file retrieval part of an automated process.
API that accepts survey-id and version-id and returns VAR-file
If only survey-id specified (no version-id), return VAR-file for current (latest) uploaded script
Pro: For a survey that is running in Nfield, user doesn’t first have to get the script (through API) to then push it into API to get VAR-file. In the total automation process, this should not be an issue at all.
Con: User can only get VAR-file for script that has been published in Nfield.
The version ID for the published test and live link can be obtained through the INfieldSurveyPackageService service.

[Story] Get VAR file for questionnaire

---

Library/Models/SurveyDownloadDataRequest.cs
Library/Services/Implementation/NfieldSurveyDataService.cs

Add interview id parameter used for downloading the data for a single respondent (for GDPR purposes)

[STORY] Add interview parameter for data download

---

Library/Services/Implementation/NfieldSurveysSearchService.cs
Tests/Services/NfieldSurveysSearchServiceTests.cs

Public API call to search respondent surveys has changed to `v1/Surveys/Search?value={value}` so we need to fix the SDK.

Use encoded query string to provide search value

---

Library/Models/SamplingPointQuotaTarget.cs
Library/Services/Implementation/NfieldSurveysService.cs
Tests/Services/NfieldSurveysServiceTests.cs

To fix the [issue 385](https://github.com/NIPOSoftwareBV/nfield/issues/385) we need to make the LevelId property public.
We also added valildation for the mandatory parameters and some unit tests for that validation.

Changes needed to fix issue 385

---

Library/Models/SamplingPointQuotaTarget.cs
Library/Properties/AssemblyInfo.cs

Instead of making the property internal for everyone, give visibility to Nfield.Manager.Api.IntegrationTests

Give visibility to Nfield.Manager.Api.IntegrationTests

---

Library/Models/SamplingPointQuotaTarget.cs
Library/Properties/AssemblyInfo.cs
Library/Services/Implementation/NfieldSurveysService.cs
Tests/Services/NfieldSurveysServiceTests.cs

To fix the [issue 385](https://github.com/NIPOSoftwareBV/nfield/issues/385) we need to make the LevelId property public.
We also added valildation for the mandatory parameters and some unit tests for that validation.
Related:
- Actual fix for the test in nfield source: https://github.com/NIPOSoftwareBV/nfield-source/pull/2242
- Update package in glu api: https://github.com/NIPOSoftwareBV/project-glu-api/pull/1613

[Issue] Purple/ci fix issue 385

---

Library/Infrastructure/ActiveDirectoryNfieldHttpClient.cs
Library/Infrastructure/DefaultNfieldHttpClient.cs
Library/Infrastructure/INfieldConnection.cs
Library/Infrastructure/INfieldHttpClient.cs
Library/Infrastructure/NfieldConnection.cs
Library/Infrastructure/NfieldConnectionFactory.cs
Library/Infrastructure/NfieldHttpClientBase.cs
Library/Infrastructure/NfieldSdkInitializer.cs
README.md
Tests/Infrastructure/NfieldConnectionTests.cs
Tests/Infrastructure/NfieldSdkInitializerTests.cs

This PR moves the spot where the current token is kept to the NfieldConnection, while keeping the logic for the refresh in the client.
It also introduces a new client, to be used when doing Active Directory authentication.

Add new client

---

Library/Nfield.SDK.csproj

Now that our SDK is on 4.5.2+ we should really upgrade this package as it was restricting the Microsoft.Http package to the last version supported on 4.0 which causes trouble for consumer running on higher framework versions.

Upgrade System.Net.Http package

---

README.md
createnugetversion.ps1
prerelease.ps1
publish-release.ps1

See documentation at https://github.com/NIPOSoftwareBV/Nfield-Documentation/pull/765
Also related https://github.com/NIPOSoftwareBV/Nfield-Tools/pull/325
Changes here:
- explain versioning in readme
- removing file used in old appveyor build
- add script to be used at the end of the SDK package build to publish the github release

[Story] Improve automation in SDK release

---

Library/Nfield.SDK.csproj

This PR is part of the feature to support max targets. Until now all our quota targets have been minimum target with the exception of overall target which indicated the maximum allowed number of interviews. In this story we extended the system so that for each quota level it is now also possible to configure the max target. This new number is optional can be mixed and matched with the existing minimum target. A big advantage of the combination of minimum and maximum target is that the user is now able to configure 'bands'.
In the past given the following frame:
| Name | Min | Max |
| --- | --- | --- |
| Target | - | 50|
| Male | 15 | - |
| Female | 25 | - |
The quota could be filled with 15 males and 35 female, but now with max targets you can the maximum variation in filling
| Name | Min …

[Story] Support max quota targets

---

Library/Services/Implementation/NfieldSurveyGroupAssignmentsService.cs
Tests/Services/NfieldSurveyGroupAssignmentsServiceTests.cs

I removed the unassign tests, because they are not really testing anything.
Even without any mock setup, PutAsJsonAsync would return NoContent so the tests actually don't prove anything.

No dashes in URLs

---

Library/Infrastructure/NfieldSdkInitializer.cs
Library/Models/SurveyChannel.cs
Library/Models/SurveyResources.cs
Library/Services/INfieldSurveyResourcesService.cs
Library/Services/Implementation/NfieldSurveyResourcesService.cs
Tests/Services/NfieldSurveyResourcesServiceTests.cs

AB#60267
[Issue #1834](https://github.com/NIPOSoftwareBV/nfield/issues/1834)
New controller in the public API for retrieving all the survey resources has been created, this controller supports Odata filtering.

Issue [#1834]: Extend API with calls for Management Tab

---

Examples/Program.cs
Library/Models/SurveyDownloadDataRequest.cs

[AB#66561](https://niposoftware.visualstudio.com/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/66561)
This is part of the feature [Download data for a specific version of the survey](https://github.com/NIPOSoftwareBV/Nfield-Documentation/blob/master/features/Download-Data-For-Specific-Survey-Version/grooming-notes.md)
- Update SurveyDownloadDataRequest model
- Update example, filtering sample data download with the SurveyVersion

[Story] Extend download (filter by Etag and include VAR file) (#66561)

---

Library/Infrastructure/NfieldSdkInitializer.cs
Library/Models/QuotaFrame.cs
Library/Models/QuotaFrameLevel.cs
Library/Models/QuotaFrameLevelTarget.cs
Library/Models/QuotaFrameVariable.cs
Library/Models/QuotaFrameVersion.cs
Library/Services/INfieldQuotaService.cs
Library/Services/Implementation/NfieldQuotaService.cs
Tests/Services/NfieldQuotaServiceTests.cs
version.txt

Since it is now possible to change quota during fieldwork, some new endpoints were added to query previous frames like is possible in the Nfield Manager.

Versioned quota through public API

---

Library/Infrastructure/NfieldSdkInitializer.cs
Library/Models/SamplingMethodModel.cs
Library/Models/SamplingMethodType.cs
Library/Services/INfieldSurveySamplingMethodService.cs
Library/Services/Implementation/NfieldSurveySamplingMethodService.cs
Tests/Services/NfieldSurveySamplingMethodTests.cs
version.txt

Support calling the  SamplingMethod endpoints in the SDK.
See also [nfield-source](https://github.com/NIPOSoftwareBV/nfield-source/pull/5924)
See also [glu-api](https://github.com/NIPOSoftwareBV/project-glu-api/pull/2853)
[AB#77421](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/77421)

[story] Create CAPI Basic Survey by API in Nfield Manager

---

CodeAnalysis/NipoSoftware.DefaultProjectRules.targets
Library/Nfield.SDK.csproj
Nfield.SDK.sln

[AB#85340](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/85340)
The package [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers) has been deprecated in favor of [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/).
`Microsoft.CodeAnalysis.NetAnalyzers` is much [more conservative](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview#enabled-rules) compared to `Microsoft.CodeAnalysis.FxCopAnalyzers`.
We therefor set the `AnalysisMode` to `AllEnabledByDefault`. (see [migration steps](https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers?view=vs-2019#migration-steps) …

Swap CodeAnalysis.FxCopAnalyzers for CodeAnalysis.NetAnalyzers

---

CodeAnalysis/NipoSoftware.DefaultProjectRules.targets

'Warnings as Errors' is very annoying while working on code. For example, unused variables are not allowed, which is common while code is not yet finished.
With this PR warnings as errors is enabled for release builds but not debug builds in all repos.
Running tests were not required.

[AB#88530] Code analysis: disable "warnings as error" in debug builds

---

Library/Services/INfieldFieldworkOfficesService.cs
Library/Services/Implementation/NfieldFieldworkOfficesService.cs
Postman/FieldworkOffices.postman_collection.json
Tests/Services/NfieldFieldworkOfficesServiceTests.cs
version.txt

Story: [AB#95126](https://dev.azure.com/niposoftware/Nfield/_workitems/edit/95126/)
Related PRs:
[Spike document](https://github.com/NIPOSoftwareBV/Nfield-Documentation/pull/2752) (read first)
[Offices endpoint in Public API](https://github.com/NIPOSoftwareBV/nfield-source/pull/6788)

Nfield API - Add missing endpoints (spike and first controller implementation)

---

Library/Infrastructure/NfieldSdkInitializer.cs
Library/Models/DomainPasswordSettings.cs
Library/Services/INfieldDomainPasswordSettingsService.cs
Library/Services/Implementation/NfieldDomainPasswordSettingsService.cs
Postman/DomainSettings.postman_collection.json
Tests/Services/NfieldDomainPasswordSettingsServiceTests.cs
Tests/Services/NfieldServiceTestsBase.cs
version.txt

[AB#95899](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/95899)
Add domain password settings endpoints to the public Api
PRs:
- https://github.com/NIPOSoftwareBV/nfield-source/pull/6859
- https://github.com/NIPOSoftware/Nfield-SDK/pull/248

AB#95899 - API: Add domain password settings endpoints

---

Library/Infrastructure/NfieldSdkInitializer.cs
Library/Models/Filter.cs
Library/Models/FilterWithOr.cs
Library/Models/InterviewerAssignmentModel.cs
Library/Services/INfieldInterviewerAssignmentsService.cs
Library/Services/INfieldSurveyInterviewerAssignmentsService.cs
Library/Services/Implementation/NfieldDomainLanguageTranslationsService.cs
Library/Services/Implementation/NfieldInterviewerAssignmentsService.cs
Library/Services/Implementation/NfieldSamplingPointInterviewerAssignmentsService.cs
Library/Services/Implementation/NfieldSurveyInterviewerAssignmentsService.cs
Library/Services/Implementation/NfieldSurveyInterviewersService.cs
Postman/InterviewerAssignments.postman_collection.json
Postman/Interviewers.postman_collection.json
Postman/SurveyInterviewersAssignments.postman_collection.json
Postman/SurveyResponseCodes.postman_collection.json
Tests/Nfield.SDK.Tests.csproj
Tests/Services/NfieldInterviewerAssignmentsServiceTests.cs
Tests/Services/NfieldSurveyInterviewerAssignmentsServiceTests.cs
Tests/Services/NfieldSurveyInterviewersServiceTests.cs
version.txt

- GET InterviewerAssignmentsAsync
- Get all the assignments of an interviewer (all surveys, sampling points...)
- Includes the quota of the assignment
- Put Assignment with the Interviewer Instructions Text
Apart of the changes in the API it includes:
- Update SDK (required to be able to update the WD tests)
- Update WD tests setup (sometimes inside the test but acting as setup) so they use the Public API endpoint instead of the Hidden API
- Access rights & Behavior would be the same as the new manager (whatever they are)
- List any missing validation + share with PM + Create issue if needed (do not add it to public Api)
Links:
* https://github.com/NIPOSoftwareBV/nfield-source/pull/6986
* https://github.com/NIPOSoftware/Nfield-SDK/pull/282
* …

API: Survey: New: Interviewer Assignments AB#97002

---

Library/Models/SurveyFieldworkCounts.cs
Library/Services/INfieldSurveyFieldworkService.cs
Library/Services/Implementation/NfieldSurveyFieldworkService.cs
Postman/SurveyFieldwork.postman_collection.json
Tests/Services/NfieldSurveyFieldworkServiceTests.cs
version.txt

API endpoint to get the survey fieldwork counts.
[AB#99039](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/99039)
PRs:
https://github.com/NIPOSoftware/Nfield-SDK/pull/290
https://github.com/NIPOSoftwareBV/nfield-source/pull/7047
Tests:

API: Survey: New: Get (ResponseCodes) Counts ab#99039

---

Postman/SurveySamplingMethod.postman_collection.json

[AB#99117](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/99117)
Survey Sampling Method had already been implemented in the past in the public Api, but didn't have a postman file.
PRs:
- https://github.com/NIPOSoftwareBV/nfield-source/pull/7063
- https://github.com/NIPOSoftware/Nfield-SDK/pull/295
Tests: See https://github.com/NIPOSoftwareBV/nfield-source/pull/7063

SDK: Add postman for survey sampling method

---

Postman/SurveySamplingPointsAddresses.postman_collection.json

[AB#103423](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/103423)
Some of the exceptions managed were related to the addresses and Add some missing endpoints was useful for the testing (and we plan to do it too for Secura, so no harm)
Related PRs:
- https://github.com/NIPOSoftwareBV/nfield-source/pull/7174
- https://github.com/NIPOSoftware/Nfield-SDK/pull/301

Add Addresses to Postman

---

Postman/Nfield Public API.postman_collection.json

Create path parameter variables in endpoints that have it instead of collection variables to make the collection easier to export to a openapi 3.0 schema that can be used 
[AB#105142](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/105142)

Fix Postman Swagger Compatibility ab#105142

---

Library/Models/CapiInterviewers/CapiInterviewer.cs
Library/Models/CapiInterviewers/CreateCapiInterviewer.cs
Library/Models/CapiInterviewers/EditCapiInterviewer.cs
Library/Services/INfieldCapiInterviewersService.cs
Library/Services/Implementation/NfieldCapiInterviewersService.cs
Tests/Services/NfieldCapiInterviewersServiceTests.cs

Fixes that you cannot set a password when creating / updating the interviewer. Removes separately updating the password (you can use Update for that). When retrieving an interviewer, the password is not provided (so you can only set it, not read it).
[#105899](https://dev.azure.com/niposoftware/Nfield/_sprints/taskboard/Team%20Yellow/Nfield/Release%202022/2022%20P1S4?workitem=105899)

Password back in the editable model, remove password specific methods, cleanup

---

Library/Models/InterviewerAssignmentModel.cs

Fix the WebDriver tests that after enabling the toggle, were failing because of the survey assignments:
- TestAssignAsync_WhenInterviewerAddedToSurvey_CheckItsAssigned("2EurobarometerSurvey", SurveyType.EuroBarometer, false)
- TestUnassignAsync_WhenInterviewerAssignedToSurvey_CheckItsUnassigned("4EurobarometerSurvey", SurveyType.EuroBarometer, false)
- TestUnassignAsync_WhenInterviewerNotAddedToSurvey_DoesntThrow("3EurobarometerSurvey", SurveyType.EuroBarometer, false)
- TestDistributeAsync_WhenInterviewerAddedToSurvey_DoesntThrows("EurobarometerSurvey", SurveyType.EuroBarometer, false)
- TestAssignAsync_WhenInterviewerNotAddedToSurvey_Throws("1EurobarometerSurvey", SurveyType.EuroBarometer, false)
- SyncStatusCapiAndManagerTests.TestUnassignedInterviewer_SyncStatusUnchanged()
- …

Fix Interviewer assignment tests

---

Library/Models/InterviewerAssignmentModel.cs
version.txt

[AB#104332](https://niposoftware.visualstudio.com/Nfield/_workitems/edit/104332)
- Fix the WebDriver tests that after enabling the toggle, were failing because of the survey assignments. The problem was that we were assigning/unassigning the interviewer from the survey. But the survey has sampling points, you need to assign/unassign from the sampling point, not the survey. Before it was allowed (but we shouldn't do that, because it doesn't have the expected behavior). For the tests it was fine, because we were just checking the Assignment table, and not the SamplingPoint assignment table.
After using the correct method, the `GetInterviewerAssignmentsAsync`. When the assignment doesn't exist, we get null in the Assigned and Active columns. That was always the case, but because in the tests …

[AB#104332] Fix WebDriver tests when address toggle is enabled

---

Library/Models/InterviewDetailsModel.cs

[AB#116000](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/116000)
- Add obsolete attribute to StartDate property
PRs:
- https://github.com/NIPOSoftwareBV/nfield-source/pull/7758
- https://github.com/NIPOSoftware/Nfield-SDK/pull/349

Public Api: interview quality startdate obsolete

---

devops.yml

We temporarily disabled the tests in the pipeline because they are blocking the build (and package creation). 
For some reason the tests hang and don't complete.

[Fix] Disable blocking tests 

---

Postman/Nfield Public API.postman_collection.json

The owner property is optional in the GeneralSettings endpoints, that's why I didn't add it there (same happens with ExcludeFromAutomaticCleanup)

Add information about deprecated endpoints

---

Library/Models/Events/CreateEventSubscriptionModel.cs
Library/Models/Events/CreatedEventSubscriptionModel.cs
Library/Models/Events/UpdateEventSubscriptionModel.cs
Library/Services/INfieldEventSubscriptionsService.cs
Library/Services/Implementation/NfieldEventSubscriptionsService.cs
Tests/Services/NfieldEventSubscriptionsServiceTests.cs

Related story: [AB#130338](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/130338)
Fix the Events Model to allow proper response/request serialization
**Implementation**

Fix events models

---

Library/Models/CopyableSurveyConfiguration.cs
version.txt

This story brings: "blueprints now support questionnaire scripts, so we should also support buttons and messages as they are also part of the questionnaire."
The story on our board: [AB#131136](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/131136) 
Tests run:
All PRs:
- https://github.com/NIPOSoftwareBV/project-glu-client/pull/6250
- https://github.com/NIPOSoftwareBV/project-glu-api/pull/5470
- https://github.com/NIPOSoftwareBV/Nfield-SDK/pull/450
- https://github.com/NIPOSoftwareBV/nfield-source/pull/8579

AB#131136 Add Buttons and Messages to Blueprint

---

Pipelines/build.yml
Pipelines/deploy-nuget.yml

[AB#132060](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/132060)
**Related PRs:**
https://github.com/NIPOSoftwareBV/nfield-source/pull/8602
https://github.com/NIPOSoftwareBV/Nfield.Quota/pull/121
https://github.com/NIPOSoftwareBV/Nfield-Tools/pull/1167
https://github.com/NIPOSoftwareBV/nfield-public-api/pull/169
**To change:**
Use always Nfield a GitHub-InstallationToken
NfieldToolsRepository to Nfield to be aligned with the pipeline triggers that are using Nfield, NfieldToolsRepository is not needed anymore
**New for specific cases:**
NipoGithubDeployment PAT to be used by DevOps GitHub[...]@1 tasks that only allow oauth and PAT Service Connections. This Github PAT has been created with the shared account nipodeployment@ktglbuc.onmicrosoft.com …

GitHub service connection

---

Library/Infrastructure/NfieldSdkInitializer.cs
Library/Services/INfieldSamplingPointsQuotaTargetsService.cs
Library/Services/INfieldSurveysService.cs
Library/Services/Implementation/NfieldSamplingPointsQuotaTargetsService.cs
version.txt

[AB#141447](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/141447)
- Remove the service related to the deleted controller
- Add a new service for the `NfieldSamplingPointsQuotaTargets `controller
---

Public api cleanup:

---

Library/Services/INfieldDeliveryRepositorySurveysService.cs
Library/Services/Implementation/NfieldDeliveryRepositorySurveysService.cs
Tests/Services/NfieldDeliveryRepositorySurveysServiceTests.cs
version.txt

Related story: [AB#141109](https://dev.azure.com/niposoftware/Nfield/_workitems/edit/141109)
Add missing RepositorySurvey endpoints in `NfieldDeliveryRepositorySurveysService`
**Implementation**
**Tests**

Add missing RepositorySurvey endpoints

---

Library/Extensions/NfieldConnectionClientExtensions.cs
Library/Models/InterviewSimulation.cs
Library/Models/InterviewSimulationFiles.cs
Library/Models/InterviewSimulationResult.cs
Library/Services/INfieldSurveyInterviewSimulationService.cs
Library/Services/Implementation/NfieldSurveyInterviewSimulationService.cs

Functions to start interview simulation using different models. One can read data directly form the file path, the other one requires the file name and the file content as a string.
Uinit tests will follow. 
---

Added start simulation functionality

---

Library/Services/INfieldSurveyInterviewSimulationService.cs
Library/Services/Implementation/NfieldSurveyInterviewSimulationService.cs

Return hint content instead of the URL (as we do for scripts)
---
@NIPOSoftwareBV/team-purple

return content

---

Library/Models/SurveyInterviewSimulation.cs
Library/Services/INfieldSurveyInterviewSimulationService.cs
Library/Services/Implementation/NfieldSurveyInterviewSimulationService.cs
Tests/Services/NfieldSurveyInterviewSimulationTests.cs

---
@NIPOSoftwareBV/team-purple

Support two new simulation endpoints

---

Library/Services/INfieldDeliveryRepositoriesService.cs
Library/Services/Implementation/NfieldDeliveryRepositoriesService.cs
Postman/Nfield Public API AAD.postman_collection.json
Tests/Services/NfieldDeliveryRepositoriesServiceTests.cs
version.txt

Related story: [AB#145686](https://dev.azure.com/niposoftware/Nfield/_workitems/edit/145686)
This PR adds support for triggering manually a repository sync
**Implementation**
**Tests**

Add sync repository endpoint

---

Library/Services/Implementation/NfieldMediaFilesService.cs

We don't support query params only path params
---

.Net8: Migrate MediaFiles, MediaFilesCount + QuotaVersions controllers

---

Library/Services/Implementation/NfieldMediaFilesService.cs

Public API supports both query params and path params but the new Public API only supports path params. We tried to make the affected endpoints compatible with both, but in .NET it seems not possible.
After checking that 0 requests were using the query params in all the production environments, we decided that it was safe to change the SDK to send the params as path params. Ironically, we are testing the endpoint by sending a query param that is not used and the help page only refers to path params `[GET v1/Surveys/{surveyId}/MediaFiles/{fileName}]`
Everything was tested manually and was working fine, however, depending on the type of params you send in the request, the encoding changes. So, file names with whitespaces are different.
- Query param: hello+world
- Path param: hello%20world …

Fix url encoding

---

Postman/Nfield Public API.postman_collection.json

Postman collection updated with a new create wave endpoint
---

Create new wave updated

---

Library/Models/SurveyDataRequest.cs

The filters introduces the possibility to download only a subset of created media files
- **IncludeCapturedMediaFiles**  This is the current one that already exists to download all media files
Include in the download the All captured Media Files during the interviews (AudioQuestion, VideoQuestion, PhotoQuestion, AudioSilentRecording)
- New  **IncludeCapturedAudioSilentRecordingFiles**
Include Audio Silent Recording captured Files during the interviews. This parameter will be ignored if IncludeCapturedMediaFiles is true
- New  **IncludeCapturedAudioQuestionFiles**
Include Audio captured Files during the interviews. This parameter will be ignored if IncludeCapturedMediaFiles is true
- New  **IncludeCapturedVideoQuestionFiles**
Include Video captured Files during the interviews. This …

Media download filter

---

Library/Services/INfieldSurveysService.cs
Library/Services/Implementation/NfieldSurveysService.cs
Tests/Services/NfieldSurveysServiceTests.cs
version.txt

Related story: [AB#161792](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/161792)
Add NRG option for surveys created out of a online blueprint.
**Implementation**
**Tests**
---
@NIPOSoftwareBV/team-green

Allow NRG Surveys to be created from a blueprint

---

Library/Infrastructure/NfieldSdkInitializer.cs
Library/Models/CopyableSurveyConfiguration.cs
Library/Models/SurveyLandingPageExportStatusResponseModel.cs
Library/Services/INfieldSurveyLandingPageService.cs
Library/Services/Implementation/NfieldSurveyLandingPageService.cs
Tests/Services/NfieldSurveyLandingPageServiceTests.cs
version.txt

[#AB168352](https://dev.azure.com/niposoftware/Nfield/_workitems/edit/168352)
This pull request introduces the ExportLandingPageAsync method to the NfieldSurveyLandingPageService, enabling users to programmatically export the landing page ZIP file for a given survey.
Summary of changes:
- Added ExportLandingPageAsync(string surveyId) to NfieldSurveyLandingPageService
- Introduced SurveyLandingPageExportStatusResponseModel to handle export response data
- Registered the landing page service in the SDK
- Added unit tests to validate both successful and failure scenarios for export/import

Add ExportLandingPage and unit tests
