- Library/Nfield.SDK.csproj
- Library/packages.config
- Tests/Nfield.SDK.Tests.csproj
- Tests/packages.config
> Move to latest Nfield.Quota package

- Library/Infrastructure/NfieldSdkInitializer.cs
- Library/Models/InvitationBatch.cs
- Library/Models/InvitationBatchWithFilter.cs
- Library/Models/InviteRespondentsStatus.cs
- Library/Models/SampleFilter.cs
- Library/Nfield.SDK.csproj
- Library/Services/INfieldSurveyInviteRespondentsService.cs
- Library/Services/Implementation/NfieldSurveyInviteRespondentsService.cs
- Tests/Nfield.SDK.Tests.csproj
- Tests/Services/NfieldSurveyInviteRespondentsServiceTests.cs
- Tests/Services/NfieldSurveySampleTests.cs
- Tests/Services/NfieldSurveyScriptServiceTests.cs
Use the public API to invite respondents.
Changes in this PR:
* Implement functionality to send an email invitation to a list of respondents
> Sending invitations to respondents

- Library/Models/InvitationTemplateModelValidated.cs
- Library/Nfield.SDK.csproj
- Library/Services/INfieldSurveyInvitationTemplatesService.cs
- Library/Services/Implementation/NfieldSurveyInvitationTemplatesService.cs
- Tests/Services/NfieldSurveyInvitationTemplatesServiceTests.cs
Implement functionality to create/update/delete invitation templates
> [Story] CRUD invitation templates

- Library/Infrastructure/NfieldSdkInitializer.cs
- Library/Models/AddInvitationImageResult.cs
- Library/Models/SampleBlockStatus.cs
- Library/Nfield.SDK.csproj
- Library/Services/INfieldSurveyInvitationImagesService.cs
- Library/Services/INfieldSurveySampleService.cs
- Library/Services/Implementation/NfieldSurveyInvitationImagesService.cs
- Library/Services/Implementation/NfieldSurveyInvitationTemplatesService.cs
- Library/Services/Implementation/NfieldSurveyInviteRespondentsService.cs
- Library/Services/Implementation/NfieldSurveySampleService.cs
- Library/Utilities/Ensure.cs
- Tests/Nfield.SDK.Tests.csproj
- Tests/Services/NfieldSurveyInvitationImagesServiceTests.cs
- Tests/Services/NfieldSurveySampleTests.cs
Implement functionality to block respondents via public API
> Add block respondent to SurveySampleService

- Library/Models/SurveyPublicId.cs
- Library/Services/INfieldSurveyPublicIdsService.cs
- Library/Services/Implementation/NfieldSurveyPublicIdsService.cs
- Tests/Services/NfieldSurveyPublicIdsServiceTests.cs
New method to be use by the WD to avoid using the hidden api. Once this is merge to the story, I will update the SDK references in WD and the other solutions
> Add method to update the survey public ids

- Library/Nfield.SDK.csproj
- Library/Services/INfieldSurveyScriptFragmentService.cs
Define the SDK interface so that we can use it for testing.
There's no implementation yet.
> CRUD script fragment interface

- Library/Infrastructure/NfieldHttpClient.cs
- Library/Models/ClearSurveySampleModel.cs
- Library/Models/SampleColumnUpdate.cs
- Library/Models/SampleUpdateStatus.cs
- Library/Models/SurveyUpdateSampleRecordModel.cs
- Library/Services/INfieldSurveySampleService.cs
- Library/Services/Implementation/NfieldSurveySampleService.cs
- Library/Utilities/Ensure.cs
- Tests/Services/NfieldSurveySampleTests.cs
New call in public SDK for the "Sample update" feature
> Added SampleUpdate call for public SDK

- Tests/Services/NfieldSurveySampleTests.cs
> Fixed unit test

- Library/Services/Implementation/NfieldDomainSearchFieldsSettingService.cs
- Tests/Services/NfieldDomainSearchFieldsSettingServiceTests.cs
and fix a wrong method name in the service
> search fields setting tests

- Library/Infrastructure/NfieldHttpClient.cs
- Library/Models/ClearSurveySampleModel.cs
- Library/Models/SampleColumnUpdate.cs
- Library/Models/SampleUpdateStatus.cs
- Library/Models/SurveyUpdateSampleRecordModel.cs
- Library/Services/INfieldSurveySampleService.cs
- Library/Services/Implementation/NfieldSurveySampleService.cs
- Library/Utilities/Ensure.cs
- Tests/Services/NfieldSurveySampleTests.cs
A new call ( `UpdateAsync` ) has been added to the SDK to update Sample data.
> [STORY]Purple/ci update sampledata

- Library/BuildPackage.cmd
- Library/Infrastructure/NfieldSdkInitializer.cs
- Library/Models/ExternalApi.cs
- Library/Models/ExternalApiHeader.cs
- Library/Services/INfieldExternalApisService.cs
- Library/Services/Implementation/NfieldExternalApisService.cs
- Nfield.SDK.sln
- Tests/Services/NfieldExternalApisServiceTests.cs
Add CRUD for External Api descriptions and headers
> [Story] Blue external api crud

- Library/Models/SurveyScript.cs
- Tests/Services/NfieldSurveyScriptServiceTests.cs
Return warning messages when an script is uploaded
> Return also warning messages when script is uploaded

- Library/Models/SurveyScript.cs
- Tests/Services/NfieldSurveyScriptServiceTests.cs
Return also the WarningMessages when the script is uploaded
Related PR: https://github.com/NIPOSoftwareBV/nfield-source/pull/2393
> [Story] Public API: Inform the user about wrong columns

- Library/Models/Survey.cs
https://github.com/NIPOSoftwareBV/nfield/issues/1102
> [Story] Expand api with surveystatus

- Library/Nfield.SDK.csproj
- Library/Properties/AssemblyInfo.cs
- Tests/Nfield.SDK.Tests.csproj
It shouldn't have been unsigned in PR #82.
> Sign the assembly again.

- Library/Models/SurveyType.cs
Prepare the SDK to accept the new SurveyType **EuroBarometerAdvanced**
> [Story] Prepare for new SurveyType EuroBarometerAdvanced

- README.md
- createnugetversion.ps1
- prerelease.ps1
- publish-release.ps1
https://github.com/NIPOSoftwareBV/Nfield-Tools/pull/319
https://github.com/NIPOSoftwareBV/Nfield-Documentation/pull/757
- explain versioning in readme
- removing file used in old appveyor build
- add script to be used at the end of the build to publish the release
> Improve automation in SDK release

- Library/Nfield.SDK.csproj
- Library/Properties/AssemblyInfo.cs
- README.md
- Tests/Nfield.SDK.Tests.csproj
- version.txt
Update the packages we changed to .NET standard and update this one to .NET Standard:
- Nfield.Quota: https://github.com/NIPOSoftware/Nfield.Quota/pull/45
> Purple/Update nipo .net standard packages 

- Library/Services/INfieldSurveyFieldworkService.cs
- Library/Services/Implementation/NfieldSurveyFieldworkService.cs
- Tests/Services/NfieldSurveyFieldworkServiceTests.cs
This adds finish field work to the sdk
> Interviewing Isolation: Move integration tests to nfield-interviewing Episode II

- Library/Nfield.SDK.csproj
- version.txt
Update Quota .net standard 2.0 package
> Nuget: Update Quota package

- Library/Nfield.SDK.csproj
Fixes Quota package version mismatch
Related PRs
https://github.com/NIPOSoftwareBV/project-glu-api/pull/1941
https://github.com/NIPOSoftwareBV/Nfield-Manager-SurveysAndSampleManagement/pull/435
https://github.com/NIPOSoftwareBV/nfield-source/pull/3413
> [STORY] Use latest quota, survey and sample package

- Library/Nfield.SDK.csproj
- version.txt
Use new quota package to support multi variables in quota.
Related PR:
https://github.com/NIPOSoftware/Nfield.Quota/pull/60
> Support multi variables in quota

- Library/Nfield.SDK.csproj
> Quota Package updated

- build.yml
Convert classic build pipelines to yaml build pipeline
> Convert to yaml build pipeline 

- devops.yml
Previous service connection does not allow editing due to AAD migration removing all rights to it
> Update service connection

- Library/Models/SurveyType.cs
- version.txt
> [Story] Introduce CATI survey type

- Library/Infrastructure/NfieldSdkInitializer.cs
- Library/Models/LocalUser.cs
- Library/Services/INfieldLocalUserService.cs
- Library/Services/Implementation/NfieldLocalUserService.cs
- Tests/Services/NfieldLocalUserServiceTests.cs
- version.txt
> [Story] CRUD for users

- Library/Infrastructure/NfieldSdkInitializer.cs
- Library/Models/AadObjectType.cs
- Library/Models/DirectoryIdentityModel.cs
- Library/Models/SurveyGroupDirectoryAssignment.cs
- Library/Models/SurveyGroupNativeAssignment.cs
- Library/Services/INfieldSurveyGroupAssignmentsService.cs
- Library/Services/Implementation/NfieldSurveyGroupAssignmentsService.cs
- Tests/Services/NfieldSurveyGroupAssignmentsServiceTests.cs
- version.txt
Pull request for [PBI 53834](https://niposoftware.visualstudio.com/DefaultCollection/Nfield/_workitems/edit/53834)
SDK updated for new API endpoints: assignments to survey groups
AB#53834
> [Story] Endpoints to assign/unassign identity

- Library/Models/SurveyScript.cs
- version.txt
We added a property to the SurveyScript model to specify if script with unfixed position is allowed
> [Story] GH#1531: Public SDK: Allow unfixed positions during upload questionnaire

- Library/Nfield.SDK.csproj
- version.txt
Update quota package.
PBI: https://niposoftware.visualstudio.com/DefaultCollection/Nfield/_workitems/edit/58760
> [Story] Support change quota

- Library/Nfield.SDK.csproj
Quota: Remove the validation for Nesting different variables under different levels (to support asymmetric quota frames)
> [STORY] Support asymmetric quota frames (Slice 1)

- devops.yml
[AB#70790](https://niposoftware.visualstudio.com/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/70790)
> more accurate description - consistent with nfield-quota

- CodeAnalysis/Standard rules for NIPO Software.ruleset
- Library/Infrastructure/NfieldConnection.cs
- Library/Infrastructure/NfieldConnectionFactory.cs
- Library/Models/Address.cs
- Library/Nfield.SDK.csproj
- Library/Services/INfieldExternalApisLogService.cs
- Library/Services/INfieldSurveyPublicIdsService.cs
- Library/Services/Implementation/NfieldCatiInterviewersService.cs
- Library/Services/Implementation/NfieldDomainEmailSettingsService.cs
- Library/Services/Implementation/NfieldDomainSearchFieldsSettingService.cs
- Nfield.SDK.sln
- Tests/Infrastructure/NfieldConnectionTests.cs
- Tests/Services/NfieldInterviewersServiceTests.cs
- Tests/Services/NfieldMediaFilesServiceTests.cs
- Tests/Services/NfieldSurveyGroupServiceTests.cs
- Tests/Services/NfieldSurveyInvitationImagesServiceTests.cs
- Tests/Services/NfieldSurveyInvitationTemplatesServiceTests.cs
- Tests/Services/NfieldSurveyInviteRespondentsServiceTests.cs
- Tests/Services/NfieldSurveyScriptFragmentServiceTests.cs
- Tests/Utilities/NfieldEncryptionUtilityTests.cs
- devops.yml
Related:
- https://github.com/NIPOSoftwareBV/nfield-storage/pull/167
- https://github.com/NIPOSoftwareBV/Nfield-Application/pull/569
- https://github.com/NIPOSoftwareBV/nfield-permissions/pull/25
- https://github.com/NIPOSoftwareBV/nfield-identity/pull/371
- https://github.com/NIPOSoftwareBV/Nfield-Capi-Interviewers/pull/449
- https://github.com/NIPOSoftwareBV/Nfield-Manager-Domains/pull/336
- https://github.com/NIPOSoftware/Nfield.Quota/pull/100
- https://github.com/NIPOSoftware/Nfield-SDK/pull/204
- https://github.com/NIPOSoftwareBV/nfield-reporting-events/pull/97
- https://github.com/NIPOSoftwareBV/nfield-nativeengine/pull/83
- https://github.com/NIPOSoftwareBV/nfield-odinparser/pull/49
- https://github.com/NIPOSoftwareBV/nfield-survey-fieldwork-package/pull/27
- …
> Add code analysers

- Library/Models/CatiInterviewer.cs
- version.txt
[AB#73049](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/73049)
Agents must have a telephone number so the dialer can call them.
> [Story] make agent available on the dialer

- Library/Models/SurveyEmailSettings.cs
- Tests/Services/NfieldSurveyEmailSettingsServiceTests.cs
- version.txt
[AB#70786](https://niposoftware.visualstudio.com/Nfield/_workitems/edit/70786)
> Add Email column property

- Library/Infrastructure/NfieldSdkInitializer.cs
- Library/Models/SamplingMethodModel.cs
- Library/Models/SamplingMethodType.cs
- Library/Services/INfieldSurveySamplingMethodService.cs
- Library/Services/Implementation/NfieldSurveySamplingMethodService.cs
- Tests/Services/NfieldSurveySamplingMethodTests.cs
- version.txt
> Basic CAPI surveys in API (add new sampling method endpoints)

- Examples/Program.cs
- Library/Models/SurveyDownloadDataRequest.cs
[AB#76768](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/76768)
- Add the new parameter in the SDK
> Issue [#2182]: Include questionnaire script in data download [Public Api]

- CodeAnalysis/NipoSoftware.DefaultProjectRules.targets
- CodeAnalysis/Standard rules for NIPO Software.ruleset
- Library/Nfield.SDK.csproj
To make it consistent with the other repos
> add code analysis targets file and remove suppressions

- Library/Models/SurveyResponseCode.cs
- Library/Services/Implementation/NfieldSurveyResponseCodesService.cs
- Tests/Services/NfieldSurveyResponseCodesServiceTests.cs
Add RelocationUrl to NfieldSurveyResponseCodesService in SDK
> Purple/Add RelocationUrl to NfieldSurveyResponseCodesService

- Library/Models/SurveyResponseCode.cs
- Library/Services/Implementation/NfieldSurveyResponseCodesService.cs
- Tests/Services/NfieldSurveyResponseCodesServiceTests.cs
- version.txt
Add RelocationUrl to NfieldSurveyResponseCodesService in SDK
> [AB#82785] Purple/Change SurveyResponseCodesController to also accept the relocation URL parameter

- Library/Infrastructure/NfieldSdkInitializer.cs
- Library/Models/MetricCounts.cs
- Library/Models/SurveyMetricCounts.cs
- Library/Models/SurveyMetrics.cs
- Library/Services/INfieldSurveyPerformanceService.cs
- Library/Services/Implementation/NfieldSurveyPerformanceService.cs
- version.txt
[AB#91876](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/91876)
> Add survey performance service

- Library/Infrastructure/NfieldSdkInitializer.cs
- Library/Models/MetricCounts.cs
- Library/Models/SurveyMetricCounts.cs
- Library/Models/SurveyMetrics.cs
- Library/Services/INfieldSurveyPerformanceService.cs
- Library/Services/Implementation/NfieldSurveyPerformanceService.cs
- version.txt
[AB#90702](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/90702)
Related PR:
- https://github.com/NIPOSoftwareBV/nfield-source/pull/6576
> [Story] Expose survey metrics through public api - AB#90702

- Library/Models/DialMode.cs
- Library/Services/INfieldSurveysService.cs
- Library/Services/Implementation/NfieldSurveysService.cs
- Tests/Services/NfieldSurveysServiceTests.cs
Add get/set dial mode api calls
> Add get/set dial mode

- Postman/FieldworkOffices.postman_collection.json
[AB#95446](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/95446)
> add offices to postman

- Library/Extensions/NfieldConnectionClientExtensions.cs
- Library/Services/Implementation/NfieldThemesService.cs
- Tests/Services/NfieldExternalApisLogDataServiceTests.cs
- Tests/Services/NfieldInterviewsServiceTests.cs
- Tests/Services/NfieldSurveySampleTests.cs
- Tests/Services/NfieldThemesServiceTests.cs
- version.txt
[AB#95768](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/95768)
Wait for the theme to be uploaded.
* https://github.com/NIPOSoftwareBV/nfield-source/pull/6852
* https://github.com/NIPOSoftware/Nfield-SDK/pull/247
> Wait for the theme to be uploaded AB#95768

- Postman/DomainLanguages.postman_collection.json
Postman collection for the DomainLanguage
> Postman collection dor the DomainLanguage

- Postman/SurveyGeneralSettings.postman_collection.json
[AB#99369](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/99369)
https://github.com/NIPOSoftwareBV/nfield-source/pull/6983
https://github.com/NIPOSoftware/Nfield-SDK/pull/280
> Add survey owner management to postman

- Library/Models/SurveyGeneralSettingsOwner.cs
- Library/Services/INfieldSurveyGeneralSettingsService.cs
- Library/Services/Implementation/NfieldSurveyGeneralSettingsService.cs
- Tests/Services/NfieldSurveyGeneralSettingsServiceTests.cs
[AB#99370](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/99370)
> Add owner management to surveyGeneralSettingsService

- Library/Models/SurveyGeneralSettingsOwner.cs
- Library/Services/INfieldSurveyGeneralSettingsService.cs
- Library/Services/Implementation/NfieldSurveyGeneralSettingsService.cs
- Postman/SurveyGeneralSettings.postman_collection.json
- Tests/Services/NfieldSurveyGeneralSettingsServiceTests.cs
- version.txt
[AB#99025](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/99025)
API: Survey: New: (Assign) Owner
PRs:
- https://github.com/NIPOSoftwareBV/nfield-source/pull/6984
- https://github.com/NIPOSoftware/Nfield-SDK/pull/281
Tests: 
- Full description in https://github.com/NIPOSoftwareBV/nfield-source/pull/6984
> API: Add survey owner management

- Postman/SurveyInterviewersAssignments.postman_collection.json
[AB#100242](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/100242)
> Get Assignments QuotaTargets Postman Collection

- Library/Services/Implementation/NfieldSurveyFieldworkService.cs
- Tests/Services/NfieldSurveyFieldworkServiceTests.cs
- version.txt
[AB#100238](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/100238)
> Response codes counts unit tests

- Library/Models/SurveyInterviewerAssignmentQuotaTargetModel.cs
- Library/Services/INfieldSurveyInterviewerAssignmentsService.cs
- Library/Services/Implementation/NfieldSurveyInterviewerAssignmentsService.cs
- Tests/Services/NfieldSurveyInterviewerAssignmentsServiceTests.cs
[AB#100244](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/100244)
[AB#100245](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/100245)
> Survey interviewer assignments targets

- Library/Services/INfieldSurveyInterviewerAssignmentsService.cs
- Library/Services/Implementation/NfieldSurveyInterviewerAssignmentsService.cs
- Postman/SurveyInterviewersAssignments.postman_collection.json
- Tests/Services/NfieldSurveyInterviewerAssignmentsServiceTests.cs
[AB#100629](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/100629)
> Get targets by interviewerid

- Library/Infrastructure/NfieldSdkInitializer.cs
- Library/Models/WorkPackage.cs
- Library/Services/INfieldSurveyInterviewerAssignmentQuotaLevelTargetsService.cs
- Library/Services/Implementation/NfieldSurveyInterviewerAssignmentQuotaLevelTargetsService.cs
- Tests/Services/NfieldSurveyInterviewerAssignmentQuotaLevelTargetsServiceTests.cs
[#AB97003](https://dev.azure.com/niposoftware/Nfield/_sprints/taskboard/Team%20Yellow/Nfield/Release%202021/2021%20Q4%20Sprint%2005?workitem=97003)
[Task](https://dev.azure.com/niposoftware/Nfield/_sprints/taskboard/Team%20Yellow/Nfield/Release%202021/2021%20Q4%20Sprint%2005?workitem=100608)
> Add service and tests

- Postman/SurveySamplingMethod.postman_collection.json
[AB#100559](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/100559)
Add postman file for the previously implemented Survey Sampling Method endpoints
Partially related to PR: https://github.com/NIPOSoftwareBV/nfield-source/pull/7049
> Add postman for survey sampling method

- Library/Services/INfieldSurveysService.cs
- Library/Services/Implementation/NfieldSurveysService.cs
- Postman/SurveyQuotaTargets.postman_collection.json
- Postman/SurveyQuotas.postman_collection.json
- Tests/Services/NfieldSurveysServiceTests.cs
Access from the survey service to the new Endpoint
[AB#100643](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/100643)
> Public API: New endpoint: Get Quota Frame

- Postman/LocalUsers.postman_collection.json
- Postman/templates_and_themes.postman_collection.json
Fix local users and templates postman collection.
[AB#101016](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/101016)
> Fix two postman collection

- Library/Models/SurveyInterviewerAssignmentQuotaTargetModel.cs
- version.txt
[AB#102015](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/102015)
Related PRs:
https://github.com/NIPOSoftwareBV/project-glu-api/pull/3682
https://github.com/NIPOSoftwareBV/nfield-source/pull/7181
> [story] Issue [#2610] Glu API Returning quota target for free intercept interviewers

- Postman/SurveySamplingPointsAddresses.postman_collection.json
[AB#103256](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/103256)
Some of the exceptions managed were related to the addresses and Add some missing endpoints was useful for the testing (and we plan to do it too for Secura, so no harm)
PRs:
- https://github.com/NIPOSoftwareBV/nfield-source/pull/7191
- https://github.com/NIPOSoftware/Nfield-SDK/pull/304
> AB#103256 - Add Addresses to Postman

- Postman/SurveyLanguages.postman_collection.json
- Postman/SurveyMove.postman_collection.json
- Postman/SurveyPackage.postman_collection.json
- Postman/SurveyPerformance.postman_collection.json
Postman public api collections:
- SurveyLanguages OBSOLETE
- SurveyMove
- SurveyPackage
- SurveyPerformance
[AB#104032](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/104032)
> Postman collection group 04

- Library/Infrastructure/NfieldSdkInitializer.cs
- Library/Models/InterviewerChanged.cs
- Library/Services/INfieldCapiInterviewersService.cs
- Library/Services/Implementation/NfieldCapiInterviewersService.cs
- Tests/Services/NfieldCapiInterviewersServiceTests.cs
- Tests/Services/NfieldLocalUserServiceTests.cs
[Task #105530](https://dev.azure.com/niposoftware/Nfield/_sprints/taskboard/Team%20Yellow/Nfield/Release%202022/2022%20P1S3?workitem=105530)
> Introduce service, copy and change tests, etc

- Library/Models/CapiInterviewers/CapiInterviewer.cs
- Library/Models/CapiInterviewers/EditCapiInterviewer.cs
- Library/Models/CapiInterviewers/NewCapiInterviewer.cs
- Library/Services/INfieldCapiInterviewersService.cs
- Library/Services/Implementation/NfieldCapiInterviewersService.cs
- Tests/Services/NfieldCapiInterviewersServiceTests.cs
> Refactoring tests and models

- Postman/Environment/DefaultTemplate.postman_environment.json
Added new properties to the GET and PATCH endpoints
> Update postman collection

- Postman/Nfield Public API.postman_collection.json
[AB#110885](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/110885)
PRs:
- https://github.com/NIPOSoftwareBV/nfield-source/pull/7509
- https://github.com/NIPOSoftware/Nfield-SDK/pull/336
> Add spare SP endpoints to postman

- Postman/Nfield Public API AAD.postman_collection.json
[AB#113413](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/113413)
[AB#113643](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/113643)
PRs:
- https://github.com/NIPOSoftwareBV/Nfield-Documentation/pull/3201
- https://github.com/NIPOSoftware/Nfield-SDK/pull/341
> Add postman AAD collection

- Postman/Nfield Public API AAD.postman_collection.json
[AB#113413](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/113413)
> AB#113413 - SDK: Add postman AAD collection

- Library/Models/SurveyDataInterviewRequest.cs
- Library/Models/SurveyDataRequest.cs
- Library/Services/INfieldSurveyDataService.cs
- Library/Services/Implementation/NfieldSurveyDataService.cs
- Tests/Services/NfieldSurveyDataServiceTests.cs
[AB#114077](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/114077)
> Add new endpoints to sdk

- Postman/Nfield Public API.postman_collection.json
[AB#114097](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/114097)
- Move all survey data calls into a "Survey/Data" folder
- Fix the tests of the classic "Get Data"
- Create new requests for the 2 new glu endpoints
> Add new endpoints to postman

- Library/Models/SurveyDataInterviewRequest.cs
- Library/Models/SurveyDataRequest.cs
- Library/Services/Implementation/NfieldSurveyDataService.cs
- Postman/Nfield Public API.postman_collection.json
- Tests/Services/NfieldSurveyDataServiceTests.cs
- version.txt
[AB#113641](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/113641)
PRs:
- https://github.com/NIPOSoftwareBV/nfield-source/pull/7668
- https://github.com/NIPOSoftware/Nfield-SDK/pull/346
> AB#113641 - (Sdk) Api survey data download

- Postman/Nfield Public API.postman_collection.json
Extend postman tests to include the new properties. Look at the changes clicking in the option to hide whitespaces
> extend tests

- Postman/Nfield Public API.postman_collection.json
[AB#109614](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/109614)
Extend postman tests to include the new properties. Look at the changes clicking in the option to hide whitespaces
> [AB#109614] Domain response codes: remove toggle

- Library/Infrastructure/NfieldSdkInitializer.cs
- Library/Models/Request.cs
- Library/Models/RequestHeader.cs
- Library/Models/RequestHttpMethod.cs
- Library/Services/INfieldRequestsService.cs
- Library/Services/Implementation/NfieldRequestsService.cs
- Postman/Nfield Public API.postman_collection.json
- Tests/Services/NfieldRequestsServiceTests.cs
- version.txt
[AB#117621](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/117621)
> Add request to SDK

- Library/Services/Implementation/NfieldRequestsService.cs
- Tests/Services/NfieldRequestsServiceTests.cs
[AB#117621](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/117621)
> Make it async

- Library/Models/CapiInterviewers/CapiInterviewer.cs
- Postman/Nfield Public API.postman_collection.json
- version.txt
[AB#117565](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/117565)
Add ClientInterviewerId to create interviewer model.
Related:
https://github.com/NIPOSoftwareBV/nfield-source/pull/7823
https://github.com/NIPOSoftwareBV/project-glu-api/pull/4407
> [AB#117565] Purple/Issue [#2793] API interviewer endpoint difference

- Library/Services/Implementation/NfieldBlacklistService.cs
- Postman/Nfield Public API.postman_collection.json
- Tests/Services/NfieldBlacklistTests.cs
- version.txt
what about the _postman_id in the postman collection json file? How does that work?
> Support download blacklist

- Library/Infrastructure/NfieldSdkInitializer.cs
- Library/Models/Request.cs
- Library/Models/RequestHeader.cs
- Library/Models/RequestHttpMethod.cs
- Library/Services/INfieldRequestsService.cs
- Library/Services/Implementation/NfieldRequestsService.cs
- Postman/Nfield Public API.postman_collection.json
- Tests/Services/NfieldRequestsServiceTests.cs
- version.txt
[AB#116867](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/116867)
Related PR:
- https://github.com/NIPOSoftwareBV/project-glu-api/pull/4391
- https://github.com/NIPOSoftware/Nfield-SDK/pull/352
- https://github.com/NIPOSoftwareBV/nfield-source/pull/7800
> [AB#116867] Story: Implement configuration for *REQUEST in public API

- Library/Services/INfieldBlacklistService.cs
- Library/Services/Implementation/NfieldBlacklistService.cs
- Postman/Nfield Public API.postman_collection.json
- Tests/Services/NfieldBlacklistTests.cs
- version.txt
See also [nfield-source](https://github.com/NIPOSoftwareBV/nfield-source/pull/7850)
[AB#116814](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/116814)
> [AB#116814] API for Downloading  blacklist email addresses

- Postman/Nfield Public API AAD.postman_collection.json
- Postman/Nfield Public API.postman_collection.json
Related [AB#118343](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/118343)
We want to have some kind of documentation for the Delivery API endpoints
> Update PublicAPI postman collection for Delivery API endpoints

- Library/Models/SurveyResources.cs
- Tests/Services/NfieldSurveyResourcesServiceTests.cs
- version.txt
[AB#118592](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/118592)
> [AB#118592] Milestone 1.1 - Marking the surveys as "will be stopped" and "will be deleted"

- Postman/Nfield Public API AAD.postman_collection.json
- Postman/Nfield Public API.postman_collection.json
Related [AB#120986](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/120986)
Update documentation for the Delivery API endpoints (Repository Users)
---
https://github.com/NIPOSoftwareBV/nfield-source/pull/8005
---
> Add Postman Documentation for Repository User (Delivery API)

- Library/Services/INfieldThemesService.cs
- Library/Services/Implementation/NfieldThemesService.cs
- Tests/Services/NfieldThemesServiceTests.cs
- version.txt
[AB#122301](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/122301)
Add possibility to add theme content as a byte array
> Add theme binary

- Postman/Environment/DefaultTemplate.postman_environment.json
- Postman/Nfield Domain API.postman_collection.json
- Postman/Nfield Public API AAD.postman_collection.json
- Postman/Nfield Public API.postman_collection.json
[AB#122433](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/122433)
People that don't work very often with the Domain API find it difficult to debug it locally
> Improve Domain API testing: Create domain api postman collection

- Postman/Nfield Domain API.postman_collection.json
- Postman/Nfield Public API.postman_collection.json
[AB#120400](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/120400)
> Update domain api postman collection with offices

- Postman/Nfield Domain API.postman_collection.json
[AB#120401](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/120401)
> Add background and search fields settings controllers to the postman collection

- Library/Models/SurveyGeneralSetting.cs
- Tests/Services/NfieldSurveyGeneralSettingsServiceTests.cs
- version.txt
[AB#123242](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/123242)
> [AB#123242] Extending Automatic deletion/stopping of surveys to survey level as optional

- Postman/Nfield Domain API.postman_collection.json
[AB#120419](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/120419)
> Api.Domain migrate DomainResponseCodes. Update Postman collection

- Library/Infrastructure/NfieldSdkInitializer.cs
- Library/Services/INfieldCapiInterviewersService.cs
- Library/Services/INfieldDomainInterviewersWorklogService.cs
- Library/Services/Implementation/NfieldCapiInterviewersService.cs
- Library/Services/Implementation/NfieldDomainInterviewersWorklogService.cs
- Tests/Services/NfieldCapiInterviewersServiceTests.cs
- Tests/Services/NfieldDomainInterviewersWorklogServiceTests.cs
[AB#124875](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/124875)
> missed methods unit tests

- Library/Models/SurveyGeneralSetting.cs
- Library/Services/INfieldSurveyGeneralSettingsService.cs
- Library/Services/Implementation/NfieldSurveyGeneralSettingsService.cs
- Postman/Nfield Public API.postman_collection.json
- Tests/Services/NfieldSurveyGeneralSettingsServiceTests.cs
- version.txt
[AB#124223](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/124223)
> [AB#124223] SurveyOtherSettings should be refactored - Move owner

- Library/Infrastructure/NfieldSdkInitializer.cs
- Library/Models/UserRoleModel.cs
- Library/Services/INfieldMeService.cs
- Library/Services/Implementation/NfieldMeService.cs
- Tests/Services/NfieldMeServiceTest.cs
[AB#124379](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/124379)
> AB#124379 Create Me Service and respective unit tests

- devops.yml
[AB#125756](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/125756)
> Remove PR trigger

- Postman/Nfield Public API AAD.postman_collection.json
- Postman/Nfield Public API.postman_collection.json
Removed deprecated calls from postman collection
> Deprecated removed

- Library/Models/DataRetentionSettings.cs
- Library/Services/INfieldDataRetentionService.cs
- Library/Services/Implementation/NfieldDataRetentionService.cs
- Postman/Nfield Public API AAD.postman_collection.json
- Postman/Nfield Public API.postman_collection.json
- Tests/Services/NfieldDataRetentionTests.cs
- Update SDK
- Update Postman collection
> Get and store data retention settings

- Postman/Nfield Public API Domain V2.postman_collection.json
- Postman/Nfield Public API-V2 (Domains).postman_collection.json
[AB#130210](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/130210)
Related PRs:
https://github.com/NIPOSoftwareBV/nfield-source/pull/8403
https://github.com/NIPOSoftwareBV/nfield-public-api/pull/142
https://github.com/NIPOSoftwareBV/Nfield-Documentation/pull/3496
> Domain API: Release V2 Block 1/2

- Library/Models/SurveyScript.cs
---
@NIPOSoftwareBV/team-white
> Add 'UseLegacyParser' to script post method.

- Library/Models/SurveyDataRequest.cs
- version.txt
Added a custom column for filtering
---
> Custom column parameters added

- version.txt
AB#129061
PRs:
https://github.com/NIPOSoftwareBV/Nfield-SDK/pull/427
https://github.com/NIPOSoftwareBV/nfield-identity/pull/1013
https://github.com/NIPOSoftwareBV/Nfield-Cati/pull/2069
https://github.com/NIPOSoftwareBV/nfield-source/pull/8428
https://github.com/NIPOSoftwareBV/project-glu-api/pull/5297
> [NPA] Start using new parser as primary parser (AB#129061)

- Library/Extensions/NfieldConnectionClientExtensions.cs
Changed GetActivityResult to use async
> Convert to async

- Nfield.SDK.sln
- Pipelines/YmlTemplates/deploy.yml
- Pipelines/YmlTemplates/runUnitTests.yml
> release pipeline improvments

- Library/Models/CapiInterviewers/CapiInterviewer.cs
- Pipelines/build.yml
- Nuget dependencies added to the package
- Missing Capi Interviewers properties
> Nuget dependencies added to the package

- Nfield.SDK.sln
- NuGet.config
- Pipelines/YmlTemplates/deploy.yml
- Pipelines/YmlTemplates/runUnitTests.yml
ab#130932
Check if the nuget is properly published.
https://github.com/NIPOSoftwareBV/Nfield-SDK/pull/436
https://github.com/NIPOSoftwareBV/Nfield.Quota/pull/116
> Pipeline Improvement. ab#130932

- Library/Services/INfieldSurveysService.cs
- Library/Services/Implementation/NfieldSurveysService.cs
- version.txt
> Remove CopyableSurveyConfiguration from AddFromBlueprintAsync

- Library/Models/CopyableSurveyConfiguration.cs
- Tests/Services/NfieldSurveysServiceTests.cs
Fix a test and add QuestionnaireScript to `CopyableSurveyConfiguration`.
---
> Forgotten stuff

- Library/Infrastructure/ActiveDirectoryNfieldHttpClient.cs
- Library/Infrastructure/DefaultNfieldHttpClient.cs
- Library/Infrastructure/NfieldConnection.cs
- Library/Services/Implementation/NfieldBlacklistService.cs
- Library/Services/Implementation/NfieldCatiInterviewersService.cs
- Library/Services/Implementation/NfieldDataRetentionService.cs
- Library/Services/Implementation/NfieldDomainInterviewersWorklogService.cs
- Library/Services/Implementation/NfieldInterviewersService.cs
- Library/Services/Implementation/NfieldLocalUserService.cs
- Library/Services/Implementation/NfieldMediaFilesService.cs
- Library/Services/Implementation/NfieldRequestsService.cs
- Library/Services/Implementation/NfieldSurveyGroupAssignmentsService.cs
- Library/Services/Implementation/NfieldSurveyGroupService.cs
- Library/Services/Implementation/NfieldSurveySampleDataService.cs
- Library/Services/Implementation/NfieldThemesService.cs
and use directly dispose instead `usings `with void body.
[AB#133497](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/133497)
> configure await false

- Library/Models/SurveyVersion.cs
- Nfield.SDK.sln
- Pipelines/deploy-nuget.yml
- Tests/Services/NfieldSurveyVersionsServiceTests.cs
- version.txt
[AB#131179](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/131179)
Report number of successfuls, droppedouts and screenedouts
Related PR's:
https://github.com/NIPOSoftwareBV/project-glu-api/pull/5453
https://github.com/NIPOSoftwareBV/nfield-source/pull/8566
> [AB#131179] Report versions with counts in public api

- Library/Infrastructure/ActiveDirectoryNfieldHttpClient.cs
- Library/Infrastructure/DefaultNfieldHttpClient.cs
- Library/Infrastructure/NfieldConnection.cs
- Library/Services/Implementation/NfieldBlacklistService.cs
- Library/Services/Implementation/NfieldCatiInterviewersService.cs
- Library/Services/Implementation/NfieldDataRetentionService.cs
- Library/Services/Implementation/NfieldDomainInterviewersWorklogService.cs
- Library/Services/Implementation/NfieldInterviewersService.cs
- Library/Services/Implementation/NfieldLocalUserService.cs
- Library/Services/Implementation/NfieldMediaFilesService.cs
- Library/Services/Implementation/NfieldRequestsService.cs
- Library/Services/Implementation/NfieldSurveyGroupAssignmentsService.cs
- Library/Services/Implementation/NfieldSurveyGroupService.cs
- Library/Services/Implementation/NfieldSurveySampleDataService.cs
- Library/Services/Implementation/NfieldThemesService.cs
- Pipelines/deploy-nuget.yml
Add configure await false to await calls.
[AB#131802](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/131802)
RT: api automated.
> Add configure await false to await calls.

- Library/Models/CopyableSurveyConfiguration.cs
- version.txt
> Add media files

- Library/Infrastructure/NfieldSdkInitializer.cs
- Library/Services/INfieldSurveyCustomColumnsService.cs
- Library/Services/Implementation/NfieldSurveyCustomColumnsService.cs
- Postman/Nfield Public API.postman_collection.json
- Tests/Services/NfieldSurveyCustomColumnsServiceTests.cs
- version.txt
[AB#134508](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/134508)
Related PR:
https://github.com/NIPOSoftwareBV/nfield-source/pull/8667
> [AB#134508] Get custom columns

- Library/Models/CopyableSurveyConfiguration.cs
- version.txt
This PR adds the option to use media files in blueprints.
The story on our board: [AB#131133](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/131133)
All PRs:
- https://github.com/NIPOSoftwareBV/project-glu-client/pull/6286
- https://github.com/NIPOSoftwareBV/project-glu-api/pull/5549
- https://github.com/NIPOSoftwareBV/Nfield-SDK/pull/454
- https://github.com/NIPOSoftwareBV/nfield-source/pull/8679
> AB#131138 Add Media files to Blueprint

- Library/Models/Interviewer.cs
- version.txt
[AB#135586](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/135586)
https://github.com/NIPOSoftwareBV/nfield/issues/2975
> Nfield SDK does not contain sync details for CAPI Interviewer

- Library/Services/Implementation/NfieldAddressesService.cs
- version.txt
[AB#138355](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/138355)
> [AB#138355] Add obsolete to addressescount

- Library/Models/LanguageTranslations.cs
- Library/Models/TranslationWarning.cs
- version.txt
> Add language translation warnings

- Library/Services/Implementation/NfieldDeliveryRepositoryUsersService.cs
- Tests/Services/NfieldDeliveryRepositoryUsersServiceTests.cs
- version.txt
[AB#133377](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/133377)
Fix delivery API endpoint Implementation
PRs:
- https://github.com/NIPOSoftwareBV/nfield-source/pull/8975
- https://github.com/NIPOSoftwareBV/Nfield-SDK/pull/461
> Fix Delivery endpoint

- Library/Services/INfieldSurveySampleService.cs
- Library/Services/Implementation/NfieldSurveySampleService.cs
- Postman/Nfield Public API.postman_collection.json
- Tests/Services/NfieldSurveySampleTests.cs
- version.txt
[AB#139853](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/139853)
Related PR:
https://github.com/NIPOSoftwareBV/nfield-source/pull/9019
> [AB#139853] Get single sample record by interview id

- Library/Models/SampleColumnCreate.cs
- Library/Services/INfieldSurveySampleService.cs
- Library/Services/Implementation/NfieldSurveySampleService.cs
- Tests/Services/NfieldSurveySampleTests.cs
[AB#141773](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/141773)
NOTE: not sure how to increment the version number
> AB#141773 Sdk Create Sample Record

- Library/Models/SampleColumnCreate.cs
- Library/Services/INfieldSurveySampleService.cs
- Library/Services/Implementation/NfieldSurveySampleService.cs
- Tests/Services/NfieldSurveySampleTests.cs
- version.txt
[AB#124388](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/124388)
Related PRs:
https://github.com/NIPOSoftwareBV/project-glu-api/pull/5864
https://github.com/NIPOSoftwareBV/nfield-source/pull/9062
> Single sample record creation with auto generated respondentKey

- Library/Services/INfieldSurveySampleService.cs
- Library/Services/Implementation/NfieldSurveySampleService.cs
- Tests/Services/NfieldSurveySampleTests.cs
[AB#142027](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/142027)
---
> AB#142027 Yellow/where clause surveysample tests

- Library/Services/INfieldSurveySampleService.cs
- Library/Services/Implementation/NfieldSurveySampleService.cs
- Tests/Services/NfieldSurveySampleTests.cs
- version.txt
[AB#139011](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/139011)
[AB#142027](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/142027)
[AB#140978](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/140978)
> AB#139011 Yellow/ci where clause surveysample tests

- Postman/Nfield Public API.postman_collection.json
[AB#143532](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/143532)
> AB#143532 Update Nfield Public API.postman_collection.json

- Library/Services/INfieldExternalApisService.cs
- Library/Services/Implementation/NfieldExternalApisService.cs
- Postman/Nfield Public API.postman_collection.json
- Tests/Services/NfieldExternalApisServiceTests.cs
- version.txt
[AB#137553](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/137553)
> AB#137553 Remove option to create new *GETDATA endpoint through Manager and Public API

- Library/Infrastructure/NfieldSdkInitializer.cs
- Library/Services/INfieldSurveySimulationHintsService.cs
- Library/Services/Implementation/NfieldSurveySimulationHintsService.cs
- Postman/Nfield Public API.postman_collection.json
- Tests/Services/NfieldSurveySimulationHintsTests.cs
- add download hints api to sdk
- update postman
- add tests
---
@NIPOSoftwareBV/team-purple
> Add download hints api

- CodeAnalysis/NipoSoftware.DefaultProjectRules.targets
- Library/Nfield.SDK.csproj
- Nfield.SDK.sln
- Tests/Nfield.SDK.Tests.csproj
- version.txt
[AB#140570](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/140570)
> AB#140570 Use new table storage methods/types in project-glu-api

- Library/Services/INfieldMediaFilesService.cs
- Library/Services/Implementation/NfieldMediaFilesService.cs
- version.txt
[AB#145644](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/145644)
---
> AB#145644 return activity Id from MediaFileUpload

- Library/Services/INfieldSurveyInterviewSimulationService.cs
- Tests/Services/NfieldSurveyInterviewSimulationTests.cs
> Fixed test

- Library/Infrastructure/FileBase.cs
- Library/Infrastructure/FileWrapper.cs
- Library/Models/InterviewSimulation.cs
- Library/Services/Implementation/NfieldSurveyInterviewSimulationService.cs
- Tests/Services/NfieldSurveyInterviewSimulationTests.cs
Upload sample data as binary
---
> Send sample data as binary

- Postman/Nfield Public API AAD.postman_collection.json
- Postman/Nfield Public API.postman_collection.json
Update Public API and Public API AAD postman collections
The following actions were wrong:
- Activate sampling points 
- Replace sampling points
> Fix postman collection

- Postman/Nfield Public API Domain V2.postman_collection.json
- Postman/Nfield Public API.postman_collection.json
`MinCharsetsInPassword` & `MinPasswordLength` can no longer be updated, so they have been removed in the PATCH example.
---
> Remove properties from patch

- Library/Models/WaveSurvey.cs
- Library/Services/Implementation/NfieldParentSurveyWavesService.cs
- Tests/Services/NfieldParentSurveyWavesServiceTests.cs
Copy wave artifacts when creating a new wave
---
> Add wave survey with artifacts copy

- Library/Models/Survey.cs
- version.txt
[AB#151742](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/151742)
Main PR:
- https://github.com/NIPOSoftwareBV/project-glu-api/pull/6601
> Add EnableRespondentsGateway to survey model

- Library/Models/ParentSurvey.cs
- Library/Models/ParentSurveyWave.cs
- Library/Models/ParentSurveyWaveCopy.cs
- Library/Services/INfieldParentSurveyService.cs
- Library/Services/INfieldParentSurveyWavesService.cs
- Library/Services/Implementation/NfieldParentSurveyService.cs
- Library/Services/Implementation/NfieldParentSurveyWavesService.cs
- Tests/Services/NfieldParentSurveyServiceTests.cs
- Tests/Services/NfieldParentSurveyWavesServiceTests.cs
- version.txt
[AB#151199](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/151199)
Related PRs:
https://github.com/NIPOSoftwareBV/nfield-public-api/pull/513
https://github.com/NIPOSoftwareBV/nfield-source/pull/9848
> Parent and Waves Isolated models

- Library/Models/SurveySettingEnum.cs
- Library/Models/SurveySettings.cs
- Library/Services/INfieldSurveySettingsService.cs
- Library/Services/Implementation/NfieldSurveySettingsService.cs
[AB#156254](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/156254)
---
> setting enum

- Library/Models/SurveySettingEnum.cs
- Library/Models/SurveySettings.cs
- Library/Services/INfieldSurveySettingsService.cs
- Library/Services/Implementation/NfieldSurveySettingsService.cs
Define a new survey setting for GPS CONTINUOUS TRACKING
[Feature](https://github.com/NIPOSoftwareBV/nfield/issues/3167)
https://github.com/NIPOSoftwareBV/nfield-public-api/pull/598
https://github.com/NIPOSoftwareBV/Nfield-SDK/pull/539
https://github.com/NIPOSoftwareBV/project-glu-api/pull/6807
https://github.com/NIPOSoftwareBV/nfield-source/pull/9949
[AB#145742](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/145742)
> Define a new survey setting for GPS CONTINUOUS TRACKING

- version.txt
> SDK EOS Release

- Library/Models/SurveySettingEnum.cs
- Library/Models/SurveySettings.cs
- Library/Services/INfieldSurveySettingsService.cs
- Library/Services/Implementation/NfieldSurveySettingsService.cs
- version.txt
[AB#156616](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/156616)
> Remove GetManualTestSurvey endpoint

- Library/Models/InterviewQuality.cs
- Tests/Services/NfieldInterviewQualityServiceTests.cs
- version.txt
[AB#160659](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/160659)
Related pr's: 
[web client](https://github.com/NIPOSoftwareBV/project-glu-client/pull/7334)
[glu api](https://github.com/NIPOSoftwareBV/project-glu-api/pull/7003)
[public api](https://github.com/NIPOSoftwareBV/nfield-public-api/pull/739)
> Quality control new states: New “mark to reject” state

- Library/Models/Survey.cs
- Tests/Services/NfieldParentSurveyServiceTests.cs
- version.txt
The Survey model updated with LastStartDate and HasStartedWave
---
> Updated Survey model

- Library/Models/SamplingPoint.cs
- Library/Models/SamplingPointCustomDataModel.cs
- Tests/Services/NfieldSamplingPointsServiceTests.cs
[AB#160614](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/160614)
Adds Sampling point sample data features
Related PR: 
https://github.com/NIPOSoftwareBV/project-glu-api/pull/7134
https://github.com/NIPOSoftwareBV/nfield-public-api/pull/898
> New Sampling point features Create and Patch 

- Library/Models/LandingPageUploadStatusResponseModel.cs
- Library/Services/INfieldLandingPageService.cs
- Library/Services/Implementation/NfieldLandingPageService.cs
https://dev.azure.com/niposoftware/Nfield/_workitems/edit/168352
---
> Create Landing Page Service

- Library/Infrastructure/NfieldSdkInitializer.cs
- Tests/Services/NfieldSurveyLandingPageServiceTests.cs
- version.txt
add unit test; register the service; fix version;
---
> Add unit tests to new landing page service

- Library/Models/SurveyLandingPageExportStatusResponseModel.cs
- Library/Services/INfieldSurveyLandingPageService.cs
- Library/Services/Implementation/NfieldSurveyLandingPageService.cs
- Tests/Services/NfieldSurveyLandingPageServiceTests.cs
> Add export landing page feature and tests

- Library/Models/SurveyScript.cs
[AB#170020](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/170020)
---
@NIPOSoftwareBV/team-white
> Mark UseLegacyParser obsolete and stop sending it
